### ISSUE TITLE
No audio output

### ISSUE THREAD

**Issue by davide24** [jgilchrist/gbemu#10]
Hi :-)
i was able to build the emulator following the instructions of the readme file. Just a question, the audio is available at the moment or it has to be add?
I ask you that because at the moment i have no audio output and I don't know if I am missing some dependencies or I need to put some specific option on the cli when I run the emulator. I tested it with super mario land
Thanks,

**Comment by jgilchrist** [comment]
Hi @davide24, thanks for trying out gbemu! I haven't had a chance to add audio support yet - I've been working on this off-and-on and at the moment I'm working on adding support for Gameboy Color 🙂 Once I've finished GBC support and got the emulator passing Blargg's tests 100% I'll be looking to get started on audio

**Comment by jgilchrist** [comment]
I've added a23c86e1e7ed06dfc0e0ebc5193600d0c5c8021f to document that audio isn't supported yet. Thanks again!

**Comment by davide24** [comment]
Thanks! I look forward for your update! thanks :-)
