### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by sparkskapil** [jgilchrist/gbemu#8]
When i tried running make command, I am getting the following error.

CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by jgilchrist** [comment]
@sparkskapil I haven't tried building this on Windows except within WSL. That said, it looks from the error you're getting as though you don't have SDL installed. SDL is listed as a requirement [in the README](https://github.com/jgilchrist/gbemu/blob/master/README.md#building).

Are you trying to build this within WSL? If you, you can install SDL via `apt`. If you're building in some other way, you might be able to use [this page](https://wiki.libsdl.org/Installation) to install SDL.

If you have SDL installed already, CMake may not be able to find the file that it provides - you may need to follow the error's suggestion and point `CMAKE_PREFIX_PATH` at your SDL installation so it can be detected.

**Comment by jgilchrist** [comment]
@sparkskapil I'm going to close this for now as I hope I've provided a solution to your issue. If you are still experiencing difficulties, please feel free to re-open with some more details.
